apiVersion: v1
kind: Secret
metadata:
  name: proyecto-devops-secrets
  namespace: devops-staging
type: Opaque
stringData:
  APP_SECRET_KEY: "devops-secret-key"
  SPRING_DATASOURCE_USERNAME: "devops_user"
  SPRING_DATASOURCE_PASSWORD: "devops_password"
