#!/bin/sh
echo "Running Gitleaks pre-commit scan..."

REPO_PATH=$(pwd -W)

MSYS_NO_PATHCONV=1 docker.exe run --rm -v "${REPO_PATH}:/repo" zricethezav/gitleaks:latest detect --source=/repo --redact --verbose

if [ $? -ne 0 ]; then
  echo "Secrets detected or Gitleaks scan failed. Commit aborted."
  exit 1
fi

echo "No secrets detected. Commit allowed."
exit 0