global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "proyecto-devops"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "proyecto-devops-service.devops-staging.svc.cluster.local:80"