spring.application.name=proyecto-devops

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%level service=${spring.application.name} trace_id=%X{trace_id:-none} thread=%thread logger=%logger{36} message="%msg"%n

server.port=${PORT:8080}